- name: Rocket.Chat Notification
  uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@master
  if: always()
  with:
    type: ${{ job.status }}
    job_name: '*Lint Check*'
    mention: 'here'
    mention_if: 'failure'
    channel: '#random'
    url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
